[package]
name = "exshape_shape"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "exshape_shape"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.33.0"
itertools = "0.13.0"
derivative = "2.2.0"
float_extras = "0.1.6"
