[package]
name = "exshape_shape"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "exshape_shape"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.27.0"
rustler_codegen = "0.27.0"
itertools = "0.10.5"
derivative = "2.2.0"
float_extras = "0.1.6"
